version: '3'

services:
  phpfpm:
    image: evild/alpine-php:7.0.6
    container_name: php.bao.ho
    hostname: php.bao.ho
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
    networks:
      - bao.ho

  nginx:
    image: nginx:1.12
    container_name: nginx.bao.ho
    hostname: nginx.bao.ho
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
      - ./sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./sites-available/:/etc/nginx/sites-available/:ro
      - ./logs/:/var/log/nginx/
      - ./www:/data/www

networks:
  bao.ho:
    external:
      name: bao.ho.network

