version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.bao.ho
    hostname: phpmyadmin.bao.ho
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - bao.ho


networks:
  bao.ho:
    external:
      name: bao.ho.network