version: '3'

services:
  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - bao.ho


  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
       - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bao.ho

networks:
  bao.ho:
    external:
      name: bao.ho.network