version: '3'

services:
  dejavu:
    image: appbaseio/dejavu
    container_name: dejavu.bao.ho
    hostname: dejavu.bao.ho
    restart: unless-stopped
    ports:
      - "1358:1358"
    networks:
      - bao.ho


networks:
  bao.ho:
    external:
      name: bao.ho.network