version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql.bao.ho
    hostname: mysql.bao.ho
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
       - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bao.ho


networks:
  bao.ho:
    external:
      name: bao.ho.network